/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorldsRouteImport } from './routes/worlds'
import { Route as VersionsRouteImport } from './routes/versions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ServersRouteImport } from './routes/servers'
import { Route as PublicServersRouteImport } from './routes/public-servers'
import { Route as NewsRouteImport } from './routes/news'
import { Route as ModpacksRouteImport } from './routes/modpacks'
import { Route as InstallationsRouteImport } from './routes/installations'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModConfigsIdRouteImport } from './routes/mod-configs/$id'
import { Route as InstallModsIdRouteImport } from './routes/install-mods/$id'

const WorldsRoute = WorldsRouteImport.update({
  id: '/worlds',
  path: '/worlds',
  getParentRoute: () => rootRouteImport,
} as any)
const VersionsRoute = VersionsRouteImport.update({
  id: '/versions',
  path: '/versions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ServersRoute = ServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicServersRoute = PublicServersRouteImport.update({
  id: '/public-servers',
  path: '/public-servers',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ModpacksRoute = ModpacksRouteImport.update({
  id: '/modpacks',
  path: '/modpacks',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallationsRoute = InstallationsRouteImport.update({
  id: '/installations',
  path: '/installations',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModConfigsIdRoute = ModConfigsIdRouteImport.update({
  id: '/mod-configs/$id',
  path: '/mod-configs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallModsIdRoute = InstallModsIdRouteImport.update({
  id: '/install-mods/$id',
  path: '/install-mods/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/installations': typeof InstallationsRoute
  '/modpacks': typeof ModpacksRoute
  '/news': typeof NewsRoute
  '/public-servers': typeof PublicServersRoute
  '/servers': typeof ServersRoute
  '/settings': typeof SettingsRoute
  '/versions': typeof VersionsRoute
  '/worlds': typeof WorldsRoute
  '/install-mods/$id': typeof InstallModsIdRoute
  '/mod-configs/$id': typeof ModConfigsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/installations': typeof InstallationsRoute
  '/modpacks': typeof ModpacksRoute
  '/news': typeof NewsRoute
  '/public-servers': typeof PublicServersRoute
  '/servers': typeof ServersRoute
  '/settings': typeof SettingsRoute
  '/versions': typeof VersionsRoute
  '/worlds': typeof WorldsRoute
  '/install-mods/$id': typeof InstallModsIdRoute
  '/mod-configs/$id': typeof ModConfigsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/installations': typeof InstallationsRoute
  '/modpacks': typeof ModpacksRoute
  '/news': typeof NewsRoute
  '/public-servers': typeof PublicServersRoute
  '/servers': typeof ServersRoute
  '/settings': typeof SettingsRoute
  '/versions': typeof VersionsRoute
  '/worlds': typeof WorldsRoute
  '/install-mods/$id': typeof InstallModsIdRoute
  '/mod-configs/$id': typeof ModConfigsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/installations'
    | '/modpacks'
    | '/news'
    | '/public-servers'
    | '/servers'
    | '/settings'
    | '/versions'
    | '/worlds'
    | '/install-mods/$id'
    | '/mod-configs/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/installations'
    | '/modpacks'
    | '/news'
    | '/public-servers'
    | '/servers'
    | '/settings'
    | '/versions'
    | '/worlds'
    | '/install-mods/$id'
    | '/mod-configs/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/installations'
    | '/modpacks'
    | '/news'
    | '/public-servers'
    | '/servers'
    | '/settings'
    | '/versions'
    | '/worlds'
    | '/install-mods/$id'
    | '/mod-configs/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  InstallationsRoute: typeof InstallationsRoute
  ModpacksRoute: typeof ModpacksRoute
  NewsRoute: typeof NewsRoute
  PublicServersRoute: typeof PublicServersRoute
  ServersRoute: typeof ServersRoute
  SettingsRoute: typeof SettingsRoute
  VersionsRoute: typeof VersionsRoute
  WorldsRoute: typeof WorldsRoute
  InstallModsIdRoute: typeof InstallModsIdRoute
  ModConfigsIdRoute: typeof ModConfigsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/worlds': {
      id: '/worlds'
      path: '/worlds'
      fullPath: '/worlds'
      preLoaderRoute: typeof WorldsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/versions': {
      id: '/versions'
      path: '/versions'
      fullPath: '/versions'
      preLoaderRoute: typeof VersionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servers': {
      id: '/servers'
      path: '/servers'
      fullPath: '/servers'
      preLoaderRoute: typeof ServersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public-servers': {
      id: '/public-servers'
      path: '/public-servers'
      fullPath: '/public-servers'
      preLoaderRoute: typeof PublicServersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modpacks': {
      id: '/modpacks'
      path: '/modpacks'
      fullPath: '/modpacks'
      preLoaderRoute: typeof ModpacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/installations': {
      id: '/installations'
      path: '/installations'
      fullPath: '/installations'
      preLoaderRoute: typeof InstallationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mod-configs/$id': {
      id: '/mod-configs/$id'
      path: '/mod-configs/$id'
      fullPath: '/mod-configs/$id'
      preLoaderRoute: typeof ModConfigsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install-mods/$id': {
      id: '/install-mods/$id'
      path: '/install-mods/$id'
      fullPath: '/install-mods/$id'
      preLoaderRoute: typeof InstallModsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  InstallationsRoute: InstallationsRoute,
  ModpacksRoute: ModpacksRoute,
  NewsRoute: NewsRoute,
  PublicServersRoute: PublicServersRoute,
  ServersRoute: ServersRoute,
  SettingsRoute: SettingsRoute,
  VersionsRoute: VersionsRoute,
  WorldsRoute: WorldsRoute,
  InstallModsIdRoute: InstallModsIdRoute,
  ModConfigsIdRoute: ModConfigsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
